set_property PACKAGE_PIN W5 [get_ports CLK] 
set_property IOSTANDARD LVCMOS33 [get_ports CLK] 

set_property PACKAGE_PIN T18 [get_ports BTNU]
set_property PACKAGE_PIN U17 [get_ports BTND]
set_property PACKAGE_PIN W19 [get_ports BTNL]
set_property PACKAGE_PIN T17 [get_ports BTNR]
set_property PACKAGE_PIN U18 [get_ports BTNC]
set_property IOSTANDARD LVCMOS33 [get_ports BTNU] 
set_property IOSTANDARD LVCMOS33 [get_ports BTND] 
set_property IOSTANDARD LVCMOS33 [get_ports BTNL] 
set_property IOSTANDARD LVCMOS33 [get_ports BTNR] 
set_property IOSTANDARD LVCMOS33 [get_ports BTNC] 

set_property PACKAGE_PIN V17 [get_ports SW0]
set_property PACKAGE_PIN V16 [get_ports SW1]
set_property PACKAGE_PIN W16 [get_ports SW2]
set_property PACKAGE_PIN W17 [get_ports SW3]
set_property PACKAGE_PIN W15 [get_ports SW4]
set_property PACKAGE_PIN V15 [get_ports SW5]
set_property PACKAGE_PIN W14 [get_ports SW6]
set_property PACKAGE_PIN U1 [get_ports SW13]
set_property PACKAGE_PIN T1 [get_ports SW14]
set_property PACKAGE_PIN R2 [get_ports SW15]

set_property IOSTANDARD LVCMOS33 [get_ports SW0] 
set_property IOSTANDARD LVCMOS33 [get_ports SW1] 
set_property IOSTANDARD LVCMOS33 [get_ports SW2] 
set_property IOSTANDARD LVCMOS33 [get_ports SW3] 
set_property IOSTANDARD LVCMOS33 [get_ports SW4] 
set_property IOSTANDARD LVCMOS33 [get_ports SW5] 
set_property IOSTANDARD LVCMOS33 [get_ports SW6] 
set_property IOSTANDARD LVCMOS33 [get_ports SW13] 
set_property IOSTANDARD LVCMOS33 [get_ports SW14] 
set_property IOSTANDARD LVCMOS33 [get_ports SW15] 

set_property PACKAGE_PIN U16 [get_ports LD0 ]
set_property PACKAGE_PIN E19 [get_ports LD1 ]
set_property PACKAGE_PIN U19 [get_ports LD2 ]
set_property PACKAGE_PIN V19 [get_ports LD3 ]
set_property PACKAGE_PIN W18 [get_ports LD4 ]
set_property PACKAGE_PIN U15 [get_ports LD5 ]   
set_property PACKAGE_PIN U14 [get_ports LD6 ]   
set_property PACKAGE_PIN N3 [get_ports  LD13]
set_property PACKAGE_PIN P1 [get_ports  LD14]
set_property PACKAGE_PIN L1  [get_ports LD15]
set_property IOSTANDARD LVCMOS33 [get_ports LD0] 
set_property IOSTANDARD LVCMOS33 [get_ports LD1] 
set_property IOSTANDARD LVCMOS33 [get_ports LD2] 
set_property IOSTANDARD LVCMOS33 [get_ports LD3] 
set_property IOSTANDARD LVCMOS33 [get_ports LD4] 
set_property IOSTANDARD LVCMOS33 [get_ports LD5] 
set_property IOSTANDARD LVCMOS33 [get_ports LD6] 
set_property IOSTANDARD LVCMOS33 [get_ports LD13] 
set_property IOSTANDARD LVCMOS33 [get_ports LD14] 
set_property IOSTANDARD LVCMOS33 [get_ports LD15] 

set_property PACKAGE_PIN W4 [get_ports {display_out[11]}] 
set_property PACKAGE_PIN V4 [get_ports {display_out[10]}] 
set_property PACKAGE_PIN U4 [get_ports {display_out[9]}] 
set_property PACKAGE_PIN U2 [get_ports {display_out[8]}] 
set_property PACKAGE_PIN W7 [get_ports {display_out[7]}] 
set_property PACKAGE_PIN W6 [get_ports {display_out[6]}] 
set_property PACKAGE_PIN U8 [get_ports {display_out[5]}] 
set_property PACKAGE_PIN V8 [get_ports {display_out[4]}] 
set_property PACKAGE_PIN U5 [get_ports {display_out[3]}] 
set_property PACKAGE_PIN V5 [get_ports {display_out[2]}] 
set_property PACKAGE_PIN U7 [get_ports {display_out[1]}] 
set_property PACKAGE_PIN V7 [get_ports {display_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {display_out[11]}]  
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[10]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[9]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[8]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[7]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[6]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[5]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[4]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[0]}] 